<a href="https://colab.research.google.com/github/yckamra/MovieLens25m-Recommender/blob/main/MovieLens_Recommender_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import auth
import zipfile
import os
import pandas as pd
import numpy as np

In [2]:
auth.authenticate_user()

!gcloud config set project movielens-recommender-451017

!gsutil cp gs://movielens-data/movielens_data.zip /content/

Updated property [core/project].
Copying gs://movielens-data/movielens_data.zip...
==> NOTE: You are downloading one or more large file(s), which would
run significantly faster if you enabled sliced object downloads. This
feature is enabled by default but requires that compiled crcmod be
installed (see "gsutil help crcmod").

\ [1 files][257.5 MiB/257.5 MiB]   21.4 MiB/s                                   
Operation completed over 1 objects/257.5 MiB.                                    


Dataset can be found at: https://www.kaggle.com/datasets/garymk/movielens-25m-dataset

In [3]:
!ls -lh /content/

total 258M
-rw-r--r-- 1 root root 258M May 19 20:39 movielens_data.zip
drwxr-xr-x 1 root root 4.0K May 14 13:38 sample_data


In [4]:
zip_path = "/content/movielens_data.zip"  # Change to your actual zip file name
extract_to = "/content/data/"  # Where to extract files

# Create directory if it doesn't exist
os.makedirs(extract_to, exist_ok=True)

# Unzip the file
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_to)

print("Extraction complete! Files are in:", extract_to)
!ls -lh /content/data/ml-25m

Extraction complete! Files are in: /content/data/
total 1.1G
-rw-r--r-- 1 root root 416M May 19 20:40 genome-scores.csv
-rw-r--r-- 1 root root  18K May 19 20:40 genome-tags.csv
-rw-r--r-- 1 root root 1.4M May 19 20:40 links.csv
-rw-r--r-- 1 root root 2.9M May 19 20:40 movies.csv
-rw-r--r-- 1 root root 647M May 19 20:40 ratings.csv
-rw-r--r-- 1 root root  11K May 19 20:40 README.txt
-rw-r--r-- 1 root root  38M May 19 20:40 tags.csv


In [5]:
genome_scores_CSV = "/content/data/ml-25m/genome-scores.csv"
genome_tags_CSV = "/content/data/ml-25m/genome-tags.csv"
links_CSV = "/content/data/ml-25m/links.csv"
movies_CSV = "/content/data/ml-25m/movies.csv"
ratings_CSV = "/content/data/ml-25m/ratings.csv"
tags_CSV = "/content/data/ml-25m/tags.csv"

ratings.csv provides us with the data needed for the context-based recommender

In [6]:
# Load ratings data
ratings_path = ratings_CSV
ratings_df = pd.read_csv(ratings_path)

print(ratings_df.head())

# Count unique users and movies
num_users = ratings_df["userId"].nunique()
num_movies = ratings_df["movieId"].nunique()

print(f"Number of Unique Users: {num_users}")
print(f"Number of Unique Movies: {num_movies}")

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510
Number of Unique Users: 162541
Number of Unique Movies: 59047


We will be using collaborative filtering for recommendations. A 2D matrix will be created for movie to user ratings with movies on x-axis and users on y-axis. For new users, we ask for a baseline amount of movies to get a starting vector, and then we use cosine similarity to find their similarity to existing users to recommend them movies. With more ratings, comes greater accuracy.

In [7]:
numpy_matrix = np.zeros((num_users, num_movies))
print(numpy_matrix)
print(numpy_matrix.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(162541, 59047)


In order to map IDs of movies and users to the 2D matrix for collaborative filtering, we will use dictionaries to create key-value pairs between ID and index within the matrix.

In [8]:
user_id_map = {}
movie_id_map = {}
user_index = 0
movie_index = 0

# Create user_id and movie_id to 2D matrix indices
for user in ratings_df["userId"]:
  if user not in user_id_map:
    user_id_map[user] = user_index
    user_index += 1

for movie in ratings_df["movieId"]:
  if movie not in movie_id_map:
    movie_id_map[movie] = movie_index
    movie_index += 1

In [11]:
    # Iterate over the rows of the DataFrame
    for index, row in ratings_df.iterrows():
        user_index = user_id_map[row["userId"]]
        movie_index = movie_id_map[row["movieId"]]
        numpy_matrix[user_index, movie_index] = row["rating"]

Streaming output truncated to the last 5000 lines.
24995095
24995096
24995097
24995098
24995099
24995100
24995101
24995102
24995103
24995104
24995105
24995106
24995107
24995108
24995109
24995110
24995111
24995112
24995113
24995114
24995115
24995116
24995117
24995118
24995119
24995120
24995121
24995122
24995123
24995124
24995125
24995126
24995127
24995128
24995129
24995130
24995131
24995132
24995133
24995134
24995135
24995136
24995137
24995138
24995139
24995140
24995141
24995142
24995143
24995144
24995145
24995146
24995147
24995148
24995149
24995150
24995151
24995152
24995153
24995154
24995155
24995156
24995157
24995158
24995159
24995160
24995161
24995162
24995163
24995164
24995165
24995166
24995167
24995168
24995169
24995170
24995171
24995172
24995173
24995174
24995175
24995176
24995177
24995178
24995179
24995180
24995181
24995182
24995183
24995184
24995185
24995186
24995187
24995188
24995189
24995190
24995191
24995192
24995193
24995194
24995195
24995196
24995197
24995198
24995199
2499

In [13]:
ratings_dataframe = pd.DataFrame(numpy_matrix)
print(ratings_dataframe.head())

   0      1      2      3      4      5      6      7      8      9      ...  \
0    5.0    3.5    5.0    5.0    3.5    4.0    3.5    3.5    5.0    4.0  ...   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
2    5.0    0.0    0.0    0.0    0.0    0.0    0.0    5.0    0.0    0.0  ...   
3    4.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4    4.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

   59037  59038  59039  59040  59041  59042  59043  59044  59045  59046  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 59047 columns]
